services:
  piper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - piper_data:/db
    networks:
      - app_network
volumes:
  piper_data:
networks:
  app_network:
    driver: bridge
